project_id = "pixel-murmur"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://127.0.0.1:4175"
additional_redirect_urls = ["http://127.0.0.1:4175/admin/objects", "https://pixelmurmur.com/admin/objects", "https://www.pixelmurmur.com/admin/objects"]
enable_signup = false

[functions.sync-instagram]
verify_jwt = false

[functions.sync-x]
verify_jwt = false
