export const objects = [
  {
    id: 'PM-001',
    name: 'Bread Power Bank',
    status: 'Just a Pixel',
    reality: 0,
    image: '/objects/pm-001-bread-power-bank.webp',
    accent: '#824817',
    href: '/objects/pm-001',
    alt: '토스트가 꽂힌 크림색 토스터 형태의 무선 보조배터리 콘셉트 렌더',
  },
  {
    id: 'PM-002',
    name: 'Cassette Memo Case',
    status: 'Maybe Real',
    reality: 20,
    image: '/objects/pm-002-cassette-memo-case.webp',
    accent: '#45423d',
    alt: '카세트테이프 형태의 크림색 데스크 메모 케이스 콘셉트 렌더',
  },
  {
    id: 'PM-003',
    name: 'Film Roll Tape',
    status: 'Making',
    reality: 50,
    image: '/objects/pm-003-film-roll-tape.webp',
    accent: '#514b3f',
    alt: '필름통과 테이프 디스펜서를 결합한 데스크 오브젝트 콘셉트 렌더',
  },
  {
    id: 'PM-004',
    name: 'Pixel Alarm Clock',
    status: 'Soon',
    reality: 80,
    image: '/objects/pm-004-pixel-alarm-clock.webp',
    accent: '#825000',
    alt: '졸린 픽셀 표정을 띄운 작은 CRT 모니터 형태의 알람시계 콘셉트 렌더',
  },
  {
    id: 'PM-005',
    name: 'Folding Mood Lamp',
    status: 'Shelved',
    reality: 0,
    image: '/objects/pm-005-folding-mood-lamp.webp',
    accent: '#4e4d45',
    alt: '작은 초승달 상태창이 있는 접이식 데스크 무드등 콘셉트 렌더',
  },
]
