const imageRoot = '/images/objects'

const toastPowerBank = {
  id: 'PM-001',
  collection: 'toast',
  name: 'Toast Charging Station',
  nameKo: '토스트 충전 스테이션',
  status: 'Just a Pixel',
  reality: 0,
  image: `${imageRoot}/pm-001-toast-charging-station/01-hero-inserted.webp`,
  accent: '#824817',
  href: '/objects/pm-001',
  alt: '크림색 토스터 충전 도크에 분리형 토스트 미니 배터리를 꽂은 콘셉트 렌더',
  category: 'Charging Object',
  variant: 'Dock + Mini Battery',
  intro: 'A desktop charging dock with a removable toast battery, designed to make power feel like a small daily ritual.',
  introKo: '하단 도크에서 충전하고 상단 토스트 배터리만 분리해 휴대하는 데스크 충전 시스템입니다.',
  statement: ['Dock it here,', 'carry it there.'],
  story: [
    'The toaster body remains on the desk as a charging station. The toast module lifts out as a compact battery that can power a phone away from the dock.',
    'Returning the module to the gold-lined slot begins charging and brings the familiar silhouette back together. Capacity, heat, contact durability, and port layout still need engineering.',
  ],
  notes: [
    ['Detachable system', 'The lower body stays on the desk as a charging dock while the toast module lifts out for portable use.'],
    ['Toast battery', 'A discreet USB-C port, indicator lights, shell seam, and bottom contacts make the bread silhouette read as a compact device.'],
    ['Dock interface', 'The gold-lined slot charges the battery, while the front display communicates idle, charging, full, and low states.'],
    ['Next test', 'Battery capacity, thermal control, charging contacts, cable routing, and repeated docking need a working sample.'],
  ],
  gallery: [
    ['hero-inserted', '01-hero-inserted.webp', '크림색 토스터 충전 도크에 분리형 토스트 미니 배터리를 꽂은 전체 제품 렌더', 'Docked view'],
    ['detachable-structure', '02-detachable-structure.webp', '손으로 토스트 미니 배터리를 도크 슬롯에서 들어 올리는 분리 구조 렌더', 'Detachable structure'],
    ['toast-battery', '03-toast-battery.webp', 'USB-C 포트와 표시등, 충전 접점이 있는 토스트 미니 보조배터리 단독 렌더', 'Portable toast battery'],
    ['empty-dock', '04-empty-dock.webp', '상단 금색 충전 슬롯과 접점이 드러난 토스터 충전 도크 단독 렌더', 'Charging dock'],
    ['hardware-detail', '05-hardware-detail.webp', '도크의 상단 충전 접점, 측면 레버, 후면 포트와 통풍구를 확대한 렌더', 'Ports and contacts'],
    ['lcd-ui-states', '06-lcd-ui-states.webp', '대기, 충전, 완충, 저전력 상태를 픽셀 아이콘으로 보여주는 LCD 화면 렌더', 'LCD states'],
    ['desk-usage', '07-desk-usage.webp', '도크에서 분리한 토스트 배터리가 케이블로 휴대폰을 충전하는 데스크 사용 장면', 'Portable use'],
    ['packaging', '08-packaging.webp', '충전 도크와 토스트 배터리, 케이블, 설명서, 종이 트레이로 구성한 패키지 렌더', 'Packaging concept'],
  ].map(([role, file, alt, label]) => ({
    role,
    src: `${imageRoot}/pm-001-toast-charging-station/${file}`,
    alt,
    label,
  })),
}

const toastTshirt = {
  id: 'PM-002',
  collection: 'toast',
  name: 'Toast T-Shirt',
  nameKo: '토스트 티셔츠',
  status: 'Just a Pixel',
  reality: 0,
  image: `${imageRoot}/pm-002-toast-tshirt/01-hero-front.webp`,
  accent: '#9a541d',
  href: '/objects/pm-002',
  alt: '버터 장식과 구운 식빵 가장자리 표현이 들어간 크림색 오버사이즈 티셔츠 정면 렌더',
  category: 'Wearable',
  variant: 'Butter',
  intro: 'A soft oversized T-shirt that borrows its color, texture, and toasted edge from a slice of bread.',
  introKo: '식빵의 결, 구운 가장자리, 녹아내리는 버터를 한 벌의 티셔츠로 옮긴 의상 콘셉트입니다.',
  statement: ['Choose your', 'toast level.'],
  story: [
    'Toast T-Shirt treats an everyday white tee like a slice waiting to be browned. The warm edge gradient gives the flat silhouette a playful, edible depth.',
    'The Butter version adds one small three-dimensional accent. Fabric, print method, and washable construction still need to be tested before the idea can leave the screen.',
  ],
  notes: [
    ['Silhouette', 'A relaxed unisex fit with dropped shoulders keeps the toast-shaped body simple and wearable.'],
    ['Surface', 'A pale bread-crumb texture sits across the fabric with a darker toasted gradient at every edge.'],
    ['Butter detail', 'The yellow chest accent is imagined as a soft raised applique with a printed melt trail.'],
    ['Next test', 'Fabric hand feel, edge-print consistency, and wash durability need physical sampling.'],
  ],
  gallery: [
    ['hero-front', '01-hero-front.webp', '버터 장식과 구운 식빵 가장자리 표현이 들어간 크림색 오버사이즈 티셔츠 정면 렌더', 'Front / Butter'],
    ['back', '02-back.webp', '식빵 테두리처럼 갈색 그러데이션이 들어간 토스트 티셔츠 뒷면 렌더', 'Back'],
    ['side-profile', '03-side-profile.webp', '토스트 티셔츠의 드롭 숄더와 옆선을 보여주는 측면 렌더', 'Side profile'],
    ['collar-fabric-detail', '03-detail-collar-fabric.webp', '갈색 골지 카라와 식빵 결 원단 표현을 확대한 티셔츠 디테일 렌더', 'Collar and fabric'],
    ['butter-detail', '04-detail-butter.webp', '토스트 티셔츠에 부착된 노란 버터 장식과 흐르는 형태를 확대한 렌더', 'Butter applique'],
    ['worn-lifestyle', '05-worn-lifestyle.webp', '따뜻한 주방에서 토스트 티셔츠를 착용한 모습을 보여주는 라이프스타일 렌더', 'Worn view'],
    ['packaging', '06-packaging.webp', '식빵 모양으로 접은 토스트 티셔츠를 투명 봉투에 담은 패키지 콘셉트 렌더', 'Packaging concept'],
  ].map(([role, file, alt, label]) => ({
    role,
    src: `${imageRoot}/pm-002-toast-tshirt/${file}`,
    alt,
    label,
  })),
}

const toastEcoBag = {
  id: 'PM-003',
  collection: 'toast',
  name: 'Toast Eco Bag',
  nameKo: '토스트 에코백',
  status: 'Just a Pixel',
  reality: 0,
  image: `${imageRoot}/pm-003-toast-eco-bag/01-hero-front.webp`,
  accent: '#8c4e1e',
  href: '/objects/pm-003',
  alt: '식빵 모양의 크림색 캔버스 몸체와 긴 손잡이가 있는 토스트 에코백 정면 렌더',
  category: 'Carry Goods',
  intro: 'A practical canvas tote shaped like one generous slice of toast, complete with browned seams and a quiet stitched mark.',
  introKo: '도톰한 식빵 한 장의 실루엣과 구운 테두리를 캔버스 가방으로 옮긴 에코백 콘셉트입니다.',
  statement: ['Carry a slice', 'every day.'],
  story: [
    'Toast Eco Bag turns the square utility of a tote into a soft bread silhouette without losing everyday capacity. The visual joke stays readable from a distance.',
    'A structured canvas body, reinforced handles, magnetic closure, and interior pocket make the concept plausible. Pattern balance and seam construction remain to be sampled.',
  ],
  notes: [
    ['Shape', 'Rounded upper corners and a gently browned perimeter create the slice silhouette without a hard novelty outline.'],
    ['Material direction', 'Heavy cotton canvas gives the body enough structure while keeping the surface soft and familiar.'],
    ['Inside', 'A magnetic closure and small hanging pocket organize daily items without changing the clean exterior.'],
    ['Next test', 'A paper pattern and weight test will decide whether the bag holds its toast shape when carried.'],
  ],
  gallery: [
    ['hero-front', '01-hero-front.webp', '식빵 모양의 크림색 캔버스 몸체와 긴 손잡이가 있는 토스트 에코백 정면 렌더', 'Front'],
    ['back', '02-back.webp', '구운 식빵 테두리 표현과 손잡이 보강 박음질을 보여주는 토스트 에코백 후면 렌더', 'Back'],
    ['side-profile', '03-side-profile.webp', '에코백의 옆폭과 입구, 두 개의 긴 손잡이를 보여주는 측면 렌더', 'Side profile'],
    ['crust-logo-detail', '04-detail-crust-logo.webp', '캔버스 원단과 갈색 테두리 봉제, TOAST 인쇄를 확대한 에코백 디테일 렌더', 'Crust and logo'],
    ['interior-pocket-detail', '05-detail-interior-pocket.webp', '자석 여밈과 내부 포켓, 손잡이 보강 박음질을 보여주는 에코백 내부 렌더', 'Interior pocket'],
    ['worn-lifestyle', '06-worn-lifestyle.webp', '밝은 상의를 입은 사람이 토스트 에코백을 어깨에 멘 라이프스타일 렌더', 'Carried view'],
    ['packaging', '07-packaging.webp', '접은 토스트 에코백을 투명 포장과 식빵 아이콘 띠지로 감싼 패키지 렌더', 'Packaging concept'],
  ].map(([role, file, alt, label]) => ({
    role,
    src: `${imageRoot}/pm-003-toast-eco-bag/${file}`,
    alt,
    label,
  })),
}

const toastPhoneCase = {
  id: 'PM-004',
  collection: 'toast',
  name: 'Toast Phone Case',
  nameKo: '토스트 폰케이스',
  status: 'Just a Pixel',
  reality: 0,
  image: `${imageRoot}/pm-004-toast-phone-case/01-hero-three-quarter.webp`,
  accent: '#934f1c',
  href: '/objects/pm-004',
  alt: '식빵 속살 질감과 구운 갈색 테두리를 입체적으로 구현한 토스트 폰케이스의 사선 후면 렌더',
  category: 'Accessory',
  intro: 'A protective phone case that turns one familiar rectangle into a slice of toast, down to the crumb, crust, and molded edge.',
  introKo: '식빵의 폭신한 속살과 바삭하게 구운 테두리를 정교한 보호 구조로 옮긴 폰케이스 콘셉트입니다.',
  statement: ['A familiar shape,', 'freshly toasted.'],
  story: [
    'A phone and a slice of bread begin with almost the same rectangle. Toast Phone Case makes that resemblance tactile through a soft crumb surface and a browned protective rim.',
    'The humor only works if the object still feels precise. Camera protection, button response, port access, grip, and wireless charging all remain part of the physical test.',
  ],
  notes: [
    ['Crust edge', 'A raised caramel rim frames the soft bread texture while protecting the screen and camera from direct contact.'],
    ['Surface', 'The porous crumb pattern is imagined as a shallow molded texture that stays tactile without trapping dust.'],
    ['Precise fit', 'Button covers, speaker holes, and the charging opening follow the phone closely so the novelty never interrupts use.'],
    ['Next test', 'A first TPU and rigid-shell sample should verify grip, wireless charging, heat, and everyday pocket wear.'],
  ],
  gallery: [
    ['hero-three-quarter', '01-hero-three-quarter.webp', '토스트 폰케이스의 식빵 질감과 카메라 보호 테두리를 보여주는 사선 후면 렌더', 'Hero view'],
    ['back', '02-back.webp', '식빵 속살 질감과 구운 갈색 테두리를 정면에서 보여주는 토스트 폰케이스 후면 렌더', 'Back'],
    ['side-profile', '03-side-profile.webp', '토스트 폰케이스의 두께와 볼륨 버튼 마감을 보여주는 측면 렌더', 'Side profile'],
    ['camera-crust-detail', '04-detail-camera-crust.webp', '카메라 보호 립과 식빵 속살, 크러스트 전환을 확대한 토스트 폰케이스 디테일 렌더', 'Camera and crust'],
    ['buttons-ports-detail', '05-detail-buttons-ports.webp', '토스트 폰케이스의 충전 포트와 스피커 홀, 버튼 마감을 확대한 디테일 렌더', 'Buttons and ports'],
    ['worn-lifestyle', '06-lifestyle.webp', '체크 패브릭 위에 놓인 토스트 폰케이스의 아침 테이블 라이프스타일 렌더', 'Everyday setting'],
    ['packaging', '07-packaging.webp', '투명 식빵 봉투와 종이 트레이에 담긴 토스트 폰케이스 패키지 콘셉트 렌더', 'Packaging concept'],
  ].map(([role, file, alt, label]) => ({
    role,
    src: `${imageRoot}/pm-004-toast-phone-case/${file}`,
    alt,
    label,
  })),
}

const toastAirpodsCase = {
  id: 'PM-005',
  collection: 'toast',
  name: 'Toast AirPods Case',
  nameKo: '토스트 에어팟 케이스',
  status: 'Just a Pixel',
  reality: 0,
  image: `${imageRoot}/pm-005-toast-airpods-case/01-hero-closed.webp`,
  accent: '#8f4c1a',
  href: '/objects/pm-005',
  alt: '식빵의 속살과 구운 갈색 테두리를 입체적으로 표현한 토스트 에어팟 케이스의 닫힌 모습',
  category: 'Accessory',
  intro: 'A compact earbud case that turns every charge into a pocket-sized slice of toast, complete with crumb, crust, hinge, and carry ring.',
  introKo: '식빵의 속살과 구운 테두리를 충전 케이스의 뚜껑, 힌지, 키링 구조로 옮긴 에어팟 케이스 콘셉트입니다.',
  statement: ['A small slice,', 'ready to carry.'],
  story: [
    'Toast AirPods Case makes a familiar charging object easier to find and more enjoyable to carry. The toast lid opens with the case instead of becoming a separate decoration.',
    'The idea depends on precise engineering. Hinge clearance, wireless charging, speaker openings, grip, and the side ring all need to survive everyday pocket and bag use.',
  ],
  notes: [
    ['Lid and hinge', 'A fitted two-part shell follows the charging case lid so the toast silhouette opens in one natural movement.'],
    ['Surface', 'A shallow crumb texture and softly browned perimeter create the bread character without adding unnecessary bulk.'],
    ['Carry ring', 'A compact side loop gives the case a secure attachment point for a keyring, strap, or bag clip.'],
    ['Next test', 'A first flexible-shell sample should verify hinge clearance, charging access, wireless charging, and pocket wear.'],
  ],
  gallery: [
    ['hero-closed', '01-hero-closed.webp', '토스트 에어팟 케이스의 식빵 질감과 측면 키링을 보여주는 닫힌 사선 렌더', 'Hero view'],
    ['open', '02-open.webp', '흰색 무선 이어버드가 들어 있는 토스트 에어팟 케이스의 열린 모습', 'Open view'],
    ['back', '03-back-hinge.webp', '토스트 에어팟 케이스의 후면 힌지와 갈색 크러스트 테두리를 보여주는 렌더', 'Back and hinge'],
    ['hinge-keyring-detail', '04-detail-hinge-keyring.webp', '토스트 에어팟 케이스의 힌지와 금속 키링 연결부를 확대한 디테일 렌더', 'Hinge and keyring'],
    ['charging-detail', '05-detail-charging-port.webp', '토스트 에어팟 케이스 하단의 충전 단자와 스피커 구멍을 확대한 디테일 렌더', 'Charging access'],
    ['worn-lifestyle', '06-lifestyle.webp', '크림색 캔버스 가방에 토스트 에어팟 케이스를 키링으로 연결한 라이프스타일 렌더', 'Carried view'],
    ['packaging', '07-packaging.webp', '투명 식빵 봉투와 종이 트레이에 담긴 토스트 에어팟 케이스 패키지 콘셉트 렌더', 'Packaging concept'],
  ].map(([role, file, alt, label]) => ({
    role,
    src: `${imageRoot}/pm-005-toast-airpods-case/${file}`,
    alt,
    label,
  })),
}

const toastCardWallet = {
  id: 'PM-006',
  collection: 'toast',
  name: 'Toast Card Wallet',
  nameKo: '토스트 카드지갑',
  status: 'Just a Pixel',
  reality: 0,
  image: `${imageRoot}/pm-006-toast-card-wallet/01-hero-three-quarter.webp`,
  accent: '#8a4b1b',
  href: '/objects/pm-006',
  alt: '식빵 모양의 크림색 몸체와 갈색 테두리, 지퍼를 갖춘 토스트 카드지갑 사선 렌더',
  category: 'Carry Goods',
  intro: 'A compact zip-around wallet that carries cards and folded notes inside one neatly toasted slice.',
  introKo: '식빵의 폭신한 속살과 구운 테두리를 카드 수납, 지폐 공간, 지퍼 구조로 옮긴 카드지갑 콘셉트입니다.',
  statement: ['Keep a slice', 'close at hand.'],
  story: [
    'Toast Card Wallet turns a small everyday essential into an object that is easy to spot and satisfying to hold. The bread surface stays soft while the browned edge gives the shape structure.',
    'A full zipper, slim gusset, divided card sleeves, and a folded-note compartment make the concept practical. Thickness and edge wear still need a physical sample.',
  ],
  notes: [
    ['Shape and size', 'The rounded toast top creates a clear silhouette while the compact square body stays easy to carry.'],
    ['Zipper', 'A fine tan zipper follows the crust edge with a small leather pull that remains comfortable in a pocket.'],
    ['Inside', 'Card sleeves and one folded-note space separate daily essentials without turning the wallet into a bulky pouch.'],
    ['Next test', 'A stitched sample should verify zipper travel, card access, edge stiffness, and long-term surface wear.'],
  ],
  gallery: [
    ['hero-three-quarter', '01-hero-three-quarter.webp', '토스트 카드지갑의 식빵 질감과 지퍼 구조를 보여주는 사선 정면 렌더', 'Hero view'],
    ['front', '02-front.webp', '두 장의 카드가 살짝 보이는 토스트 카드지갑 정면 렌더', 'Front'],
    ['open', '03-open-interior.webp', '카드 수납칸과 접은 지폐 공간을 보여주는 열린 토스트 카드지갑 내부 렌더', 'Open interior'],
    ['side-profile', '04-side-profile.webp', '토스트 카드지갑의 얇은 옆폭과 지퍼, 가죽 손잡이를 보여주는 측면 렌더', 'Side profile'],
    ['crust-zipper-detail', '05-detail-crust-zipper.webp', '식빵 속살 질감과 갈색 봉제 테두리, 지퍼를 확대한 카드지갑 디테일 렌더', 'Crust and zipper'],
    ['worn-lifestyle', '06-lifestyle.webp', '크림색 캔버스 가방 안쪽 포켓에서 토스트 카드지갑을 꺼내는 라이프스타일 렌더', 'Everyday carry'],
    ['packaging', '07-packaging.webp', '투명 식빵 봉투와 종이 트레이에 담긴 토스트 카드지갑 패키지 콘셉트 렌더', 'Packaging concept'],
  ].map(([role, file, alt, label]) => ({
    role,
    src: `${imageRoot}/pm-006-toast-card-wallet/${file}`,
    alt,
    label,
  })),
}

const toastPouch = {
  id: 'PM-007',
  collection: 'toast',
  name: 'Toast Pouch',
  nameKo: '토스트 파우치',
  status: 'Just a Pixel',
  reality: 0,
  image: `${imageRoot}/pm-007-toast-pouch/01-hero-three-quarter.webp`,
  accent: '#8b4a1b',
  href: '/objects/pm-007',
  alt: '식빵 모양의 부드러운 크림색 몸체와 갈색 테두리, 상단 지퍼를 갖춘 토스트 파우치 사선 렌더',
  category: 'Carry Goods',
  intro: 'A soft everyday pouch that turns one roomy compartment into a padded slice of toast.',
  introKo: '식빵의 폭신한 속살과 구운 테두리를 넉넉한 수납, 상단 지퍼, 내부 포켓으로 옮긴 파우치 콘셉트입니다.',
  statement: ['Room for', 'the small things.'],
  story: [
    'Toast Pouch keeps cables, cosmetics, and stationery together inside a soft bread-shaped case. Its wider gusset and flexible body clearly separate it from the smaller card wallet.',
    'A broad opening, washable lining, divided interior pockets, and a side carry loop make the concept useful beyond the visual joke. Capacity and seam strength still need physical testing.',
  ],
  notes: [
    ['Roomy shape', 'A wider gusset and flexible padded body create useful volume without losing the toast silhouette.'],
    ['Top opening', 'The zipper opens broadly across the top so small items remain visible and easy to reach.'],
    ['Inside', 'A washable lining with divided pockets keeps cables, cosmetics, or stationery from mixing together.'],
    ['Next test', 'A sewn sample should verify capacity, zipper travel, lining cleanup, and the strength of the side loop.'],
  ],
  gallery: [
    ['hero-three-quarter', '01-hero-three-quarter.webp', '부드러운 식빵 질감과 넓은 옆폭, 상단 지퍼를 보여주는 토스트 파우치 사선 정면 렌더', 'Hero view'],
    ['front', '02-front.webp', '식빵 모양 실루엣과 갈색 봉제 테두리를 정면에서 보여주는 토스트 파우치 렌더', 'Front'],
    ['open', '03-open-interior.webp', '케이블과 펜, 작은 화장품을 나누어 담은 토스트 파우치의 열린 내부 렌더', 'Open interior'],
    ['side-profile', '04-side-profile.webp', '토스트 파우치의 넓은 옆폭과 상단 지퍼, 측면 고리를 보여주는 측면 렌더', 'Side profile'],
    ['material-zipper-detail', '05-detail-material-zipper.webp', '식빵 결을 닮은 원단과 갈색 파이핑, 지퍼, 봉제 마감을 확대한 파우치 디테일 렌더', 'Material and zipper'],
    ['worn-lifestyle', '06-lifestyle.webp', '밝은 책상에서 케이블을 토스트 파우치에 정리하는 라이프스타일 렌더', 'Everyday use'],
    ['packaging', '07-packaging.webp', '재생 종이 트레이와 글라신지에 담긴 토스트 파우치 패키지 콘셉트 렌더', 'Packaging concept'],
  ].map(([role, file, alt, label]) => ({
    role,
    src: `${imageRoot}/pm-007-toast-pouch/${file}`,
    alt,
    label,
  })),
}

const toastPhoneGrip = {
  id: 'PM-008',
  collection: 'toast',
  name: 'Toast Phone Grip',
  nameKo: '토스트 폰그립',
  status: 'Just a Pixel',
  reality: 0,
  image: `${imageRoot}/pm-008-toast-phone-grip/01-hero-three-quarter.webp`,
  accent: '#d49a1f',
  href: '/objects/pm-008',
  alt: '버터가 올라간 작은 토스트 장식과 접이식 원형 구조를 갖춘 토스트 폰그립 사선 렌더',
  category: 'Accessory',
  variant: 'Butter',
  intro: 'A compact collapsible phone grip that turns a secure one-handed hold into a tiny buttered slice.',
  introKo: '작은 버터 토스트 장식과 접이식 아코디언 구조를 결합해 한 손 사용을 돕는 폰그립 콘셉트입니다.',
  statement: ['A small grip,', 'ready in hand.'],
  story: [
    'Toast Phone Grip turns the back of a phone into a small tactile object. The butter top is decorative, while the collapsible base provides a steadier one-handed hold.',
    'Six molded topping variants share one mechanism. Adhesive strength, repeated folding, surface wear, and wireless charging compatibility remain to be tested.',
  ],
  notes: [
    ['Grip mechanism', 'A two-stage flexible neck expands for a secure hold and folds back into a compact circular base.'],
    ['Collapsed profile', 'The toast top sits close to the phone when compressed so it remains practical inside a pocket or bag.'],
    ['Flavor series', 'Butter, strawberry, red bean, blueberry, peanut butter, and chocolate share one molded toast platform.'],
    ['Next test', 'A working sample should verify adhesive strength, repeated folding, finger comfort, and charging compatibility.'],
  ],
  gallery: [
    ['hero-three-quarter', '01-hero-three-quarter.webp', '버터 토스트 장식과 펼쳐진 아코디언 구조, 부착 원판을 보여주는 폰그립 사선 렌더', 'Hero view'],
    ['front', '02-front-collapsed.webp', '접이식 구조를 눌러 토스트 장식만 정면으로 보이는 폰그립 렌더', 'Collapsed front'],
    ['side-profile', '03-side-extended.webp', '토스트 상판과 두 단계 아코디언 목, 원형 부착판을 보여주는 폰그립 측면 렌더', 'Extended profile'],
    ['attached-device', '04-attached-phone.webp', '회색 스마트폰 후면 정중앙에 부착되어 펼쳐진 버터 토스트 폰그립 렌더', 'Attached view'],
    ['variant-lineup', '05-flavor-lineup.webp', '버터, 딸기잼, 팥앙금, 블루베리잼, 땅콩버터, 초콜릿 토핑을 적용한 폰그립 여섯 가지 렌더', 'Flavor series'],
    ['worn-lifestyle', '06-lifestyle.webp', '스마트폰 후면 정중앙의 토스트 폰그립을 손가락 사이에 끼워 잡은 라이프스타일 렌더', 'In hand'],
    ['packaging', '07-packaging.webp', '버터 토스트 폰그립과 접착 보호 라이너를 종이 트레이에 담은 패키지 콘셉트 렌더', 'Packaging concept'],
  ].map(([role, file, alt, label]) => ({
    role,
    src: `${imageRoot}/pm-008-toast-phone-grip/${file}`,
    alt,
    label,
  })),
}

const pagerIndexMemo = {
  id: 'PM-009',
  collection: 'stationery',
  name: 'Pager Index Memo',
  nameKo: '삐삐 인덱스 메모',
  status: 'Just a Pixel',
  reality: 0,
  image: `${imageRoot}/pm-009-pager-index-memo/01-hero-three-quarter.webp`,
  accent: '#2f9da8',
  href: '/objects/pm-009',
  alt: '길고 낮은 화면 전체에 반투명 PET 인덱스 필름이 들어간 스모크 블랙 삐삐 메모 홀더 렌더',
  category: 'Stationery',
  variant: 'PET Index Film',
  intro: 'A pager-shaped holder that turns its long display into one peelable strip of writable PET index film.',
  introKo: '삐삐의 길고 낮은 화면 전체를 한 장의 반투명 PET 인덱스 필름으로 사용하는 문구 콘셉트입니다.',
  statement: ['The screen is', 'the memo.'],
  story: [
    'Pager Index Memo replaces the electronic display with one long strip of writable PET film. Peel it from the front and use it as a durable marker for books, notes, and planners.',
    'Each refill stacks translucent strips in five colors behind the shallow bezel. Film thickness, writing performance, removable adhesion, and refill construction still need a physical sample.',
  ],
  notes: [
    ['Screen-sized strip', 'One slim PET strip fills the complete pager display, keeping the familiar long and shallow screen proportion.'],
    ['PET material', 'A translucent semi-gloss film stays flexible, accepts handwriting, and lets the page remain visible underneath.'],
    ['Front refill', 'The display bezel opens so a full stack of long strips can be replaced without a side-dispensing mechanism.'],
    ['Next test', 'A prototype should verify writing tools, removable adhesive, film curl, refill capacity, and repeated opening.'],
  ],
  gallery: [
    ['hero-three-quarter', '01-hero-three-quarter.webp', '길고 낮은 화면 전체에 노란 PET 인덱스 필름이 들어간 스모크 블랙 삐삐 메모 홀더 사선 렌더', 'Hero view'],
    ['peel-front', '02-peel-front.webp', '삐삐 화면 전체 크기의 길쭉한 PET 인덱스 필름 한 장을 정면에서 떼어내는 모습', 'Front peel'],
    ['refill-structure', '03-refill-structure.webp', '전면 베젤과 다섯 가지 색상의 긴 PET 인덱스 리필 묶음을 분리한 구조 렌더', 'Full-length refill'],
    ['material-detail', '04-material-detail.webp', '노트 위에 펼친 노랑, 분홍, 파랑, 민트, 스모크 컬러의 반투명 PET 인덱스 필름', 'PET material'],
    ['lifestyle-notebook', '05-lifestyle-notebook.webp', '삐삐 홀더에서 꺼낸 긴 PET 인덱스 필름을 노트 페이지에 붙이는 사용 장면', 'Notebook use'],
    ['variant-lineup', '06-color-lineup.webp', '블랙, 아이보리, 네이비, 올리브 컬러의 삐삐 인덱스 메모 홀더 네 가지 렌더', 'Color lineup'],
    ['packaging', '07-packaging.webp', '삐삐 홀더와 다섯 가지 색상의 긴 PET 인덱스 리필을 담은 블리스터 패키지 렌더', 'Packaging concept'],
  ].map(([role, file, alt, label]) => ({
    role,
    src: `${imageRoot}/pm-009-pager-index-memo/${file}`,
    alt,
    label,
  })),
}

export const objects = [
  toastPowerBank,
  toastTshirt,
  toastEcoBag,
  toastPhoneCase,
  toastAirpodsCase,
  toastCardWallet,
  toastPouch,
  toastPhoneGrip,
  pagerIndexMemo,
]

export const hiddenObjects = [
  {
    archiveId: 'PM-002',
    name: 'Cassette Memo Case',
    image: '/objects/pm-002-cassette-memo-case.webp',
  },
  {
    archiveId: 'PM-003',
    name: 'Film Roll Tape',
    image: '/objects/pm-003-film-roll-tape.webp',
  },
  {
    archiveId: 'PM-004',
    name: 'Pixel Alarm Clock',
    image: '/objects/pm-004-pixel-alarm-clock.webp',
  },
  {
    archiveId: 'PM-005',
    name: 'Folding Mood Lamp',
    image: '/objects/pm-005-folding-mood-lamp.webp',
  },
]

export const featuredObject = toastPowerBank

export function findObjectByPath(path) {
  return objects.find((object) => (
    object.href === path || object.legacyPaths?.includes(path)
  ))
}
